import type { Recipe } from '~/types/cocktail';

export const DEFAULT_RECIPES: Recipe[] = [
  {
    author: 'BarCraft 首席調酒師',
    base: 'Gin',
    createdAt: 1700000000000,
    desc: '這款義大利國寶級經典擁有紅寶石般深邃光澤，融合了倫敦琴酒的草本杜松子、金巴利的厚實苦甜與紅苦艾酒的草本圓潤。',
    flavors: ['flavor_bitter', 'flavor_sweet', 'flavor_herbal'],
    garnish: '新鮮橙皮捲 (Orange Twist)',
    glass: '古典杯 (Rocks Glass)',
    ice: '手鑿大方老冰 (Clear Ice Cube)',
    id: 'seed_negroni',
    image:
      'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      {
        abv: 47.3,
        amount: '30',
        brandId: 'brand_tanqueray',
        brandText: 'Tanqueray No. 10',
        name: '琴酒',
        unit: 'ml',
      },
      {
        abv: 25.0,
        amount: '30',
        brandId: 'brand_campari',
        brandText: 'Campari Bitter',
        name: '金巴利苦酒',
        unit: 'ml',
      },
      {
        abv: 16.5,
        amount: '30',
        brandId: 'brand_carpano',
        brandText: 'Carpano Antica Formula',
        name: '甜苦艾酒',
        unit: 'ml',
      },
    ],
    isFav: true,
    isLiked: false,
    likes: 128,
    method: 'Stir (攪拌法)',
    nameEn: 'Negroni',
    nameZh: '經典內格羅尼',
    steps: [
      '將調酒杯中加入大塊方冰預冷。',
      '依序注入琴酒、金巴利苦酒與甜紅苦艾酒。',
      '使用吧匙順暢攪拌約 25-30 秒至酒液冰透且充分稀釋。',
      '透過濾冰器將酒液濾入預先放好大冰塊的古典杯中。',
      '在杯口噴灑橙皮精油並將橙皮扭捲飾於杯中。',
    ],
  },
  {
    author: 'Bourbon Alchemist',
    base: 'Whiskey',
    createdAt: 1700000100000,
    desc: '調酒史上的永恆先驅。透過微量糖與芳香苦精解構波本威士忌的焦糖、香草與橡木桶深層香氣，歷久彌新。',
    flavors: ['flavor_smoky', 'flavor_sweet', 'flavor_bitter'],
    garnish: '酒漬櫻桃與橙皮 (Cherry & Orange Peel)',
    glass: '厚底古典杯 (Rocks Glass)',
    ice: '純淨大冰球 (Ice Sphere)',
    id: 'seed_old_fashioned',
    image:
      'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      {
        abv: 45.0,
        amount: '60',
        brandId: 'brand_makers_mark',
        brandText: "Maker's Mark",
        name: '波本威士忌',
        unit: 'ml',
      },
      {
        abv: 44.7,
        amount: '3',
        brandId: 'brand_angostura',
        brandText: 'Angostura Aromatic Bitters',
        name: '安格仕芳香苦精',
        unit: 'dashes',
      },
      {
        abv: 0,
        amount: '5',
        brandId: '',
        brandText: '自製甘蔗糖漿',
        name: '原色方糖 / 糖漿',
        unit: 'ml',
      },
    ],
    isFav: false,
    isLiked: false,
    likes: 95,
    method: 'Build (直調法)',
    nameEn: 'Old Fashioned',
    nameZh: '古典調酒',
    steps: [
      '在古典杯中放入原色方糖，滴入 3 Dash 安格仕芳香苦精與少量純水潤濕。',
      '用搗棒將方糖完全搗碎融化。',
      '放入一顆純淨大冰球，倒入 60ml 美格波本威士忌。',
      '以吧匙輕柔攪拌約 20 秒，噴上橙皮油後飾以頂級酒漬櫻桃。',
    ],
  },
  {
    author: 'Botanical Explorer',
    base: 'Gin',
    createdAt: 1700000200000,
    desc: '經典沁涼調酒。以亨利爵士琴酒獨特的小黃瓜與保加利亞玫瑰精華為靈魂，搭配氣泡細緻的頂級通寧水，清爽解渴。',
    flavors: ['flavor_bubbly', 'flavor_refresh', 'flavor_herbal', 'flavor_floral'],
    garnish: '薄切小黃瓜片 (Cucumber Ribbon)',
    glass: '高球杯 (Highball Glass)',
    ice: '長條老冰柱 (Ice Spear)',
    id: 'seed_gin_tonic',
    image:
      'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      {
        abv: 41.4,
        amount: '50',
        brandId: 'brand_hendricks',
        brandText: "Hendrick's Gin",
        name: '小黃瓜玫瑰琴酒',
        unit: 'ml',
      },
      {
        abv: 0,
        amount: '120',
        brandId: '',
        brandText: 'Fever-Tree 經典通寧水',
        name: '優質通寧水',
        unit: 'ml',
      },
    ],
    isFav: true,
    isLiked: false,
    likes: 182,
    method: 'Build (直調法)',
    nameEn: "Hendrick's Gin & Tonic",
    nameZh: '亨利爵士琴通寧',
    steps: [
      '高球杯預先冰鎮並放入一根修整平滑的純淨長條老冰。',
      '沿著冰塊輕輕倒入 50ml 亨利爵士琴酒。',
      '斜拿酒杯，沿著吧匙緩緩注入冰涼通寧水至九分滿以維持氣泡活躍。',
      '以吧匙由底向上輕輕提拉一次即可，杯壁貼上長薄片小黃瓜點綴。',
    ],
  },
  {
    author: 'Tropical Sips',
    base: 'Rum',
    createdAt: 1700000300000,
    desc: '古巴經典三合一極簡調酒。白蘭姆酒的甘蔗芳醇與青檸的清亮酸度達到絕妙平衡，冷冽順口。',
    flavors: ['flavor_sour', 'flavor_sweet', 'flavor_refresh'],
    garnish: '新鮮青檸輪片 (Lime Wheel)',
    glass: '碟型香檳杯 (Coupe Glass)',
    ice: '搖盪濾冰 (Straight Up)',
    id: 'seed_daiquiri',
    image:
      'https://images.unsplash.com/photo-1517456793572-1d8efd6dc135?auto=format&fit=crop&w=900&q=80',
    ingredients: [
      {
        abv: 40.0,
        amount: '60',
        brandId: 'brand_bacardi',
        brandText: 'Bacardi Carta Blanca',
        name: '白蘭姆酒',
        unit: 'ml',
      },
      {
        abv: 0,
        amount: '30',
        brandId: '',
        brandText: '鮮榨青檸',
        name: '新鮮現榨青檸汁',
        unit: 'ml',
      },
      {
        abv: 0,
        amount: '15',
        brandId: '',
        brandText: '自製 2:1 糖漿',
        name: '二號砂糖漿',
        unit: 'ml',
      },
    ],
    isFav: false,
    isLiked: false,
    likes: 110,
    method: 'Shake (搖盪法)',
    nameEn: 'Classic Daiquiri',
    nameZh: '海明威黛綺莉',
    steps: [
      '搖酒器中加入白蘭姆酒、現榨青檸汁與糖漿。',
      '裝滿硬質方形冰塊，用力有節奏地搖盪 12 秒至搖酒器外壁結霜。',
      '使用雙重濾網 (Double Strain) 將酒液細緻濾入冰透的 Coupe 杯中。',
      '置放一枚薄切青檸輪片於酒液表面。',
    ],
  },
];
