import type { BaseSpiritOption, IngredientRule, Taxonomy } from '~/types/cocktail';

export const TAXONOMY: Taxonomy = {
  brands: [
    {
      abv: 47.3,
      aliases: ['坦奎利', '添佳力', 'tanqueray', 'tanqueray 10', 'tanqueray ten', '坦奎利10號'],
      category: 'Gin',
      id: 'brand_tanqueray',
      primaryEn: 'Tanqueray No. 10 / London Dry',
      primaryZh: '坦奎利 (Tanqueray)',
    },
    {
      abv: 40.0,
      aliases: ['龐貝', '孟買', '藍鑽', 'bombay', 'bombay sapphire'],
      category: 'Gin',
      id: 'brand_bombay',
      primaryEn: 'Bombay Sapphire',
      primaryZh: '龐貝藍鑽 (Bombay Sapphire)',
    },
    {
      abv: 41.4,
      aliases: ['亨利爵士', '亨利', 'hendricks', "hendrick's", '小黃瓜琴酒'],
      category: 'Gin',
      id: 'brand_hendricks',
      primaryEn: "Hendrick's Gin",
      primaryZh: "亨利爵士 (Hendrick's)",
    },
    {
      abv: 25.0,
      aliases: ['金巴利', '康帕利', 'campari', 'campari bitter', '義大利苦酒'],
      category: 'Liqueur',
      id: 'brand_campari',
      primaryEn: 'Campari Bitter',
      primaryZh: '金巴利苦酒 (Campari)',
    },
    {
      abv: 16.5,
      aliases: ['卡帕諾', '安提卡', 'carpano', 'antica formula', 'carpano antica', '經典紅香艾酒'],
      category: 'Vermouth',
      id: 'brand_carpano',
      primaryEn: 'Carpano Antica Formula Sweet Vermouth',
      primaryZh: '卡帕諾安提卡 (Carpano Antica Formula)',
    },
    {
      abv: 40.0,
      aliases: ['百加得', '白家得', 'bacardi', 'bacardi superior', 'bacardi white'],
      category: 'Rum',
      id: 'brand_bacardi',
      primaryEn: 'Bacardi Carta Blanca',
      primaryZh: '百加得 (Bacardi)',
    },
    {
      abv: 45.0,
      aliases: ['美格', '美格波本', "maker's mark", 'makers mark', '美格紅蠟'],
      category: 'Whiskey',
      id: 'brand_makers_mark',
      primaryEn: "Maker's Mark Bourbon",
      primaryZh: "美格波本 (Maker's Mark)",
    },
    {
      abv: 44.7,
      aliases: ['安格仕', '安果', '苦精', 'angostura', 'angostura bitters', 'aromatic bitters'],
      category: 'Bitters',
      id: 'brand_angostura',
      primaryEn: 'Angostura Aromatic Bitters',
      primaryZh: '安格仕苦精 (Angostura Bitters)',
    },
  ],
  flavors: [
    {
      aliases: ['酸', '酸味', 'sour', 'tart', '檸檬'],
      icon: 'fa-lemon',
      id: 'flavor_sour',
      primaryEn: 'Sour & Tart',
      primaryZh: '酸爽清新',
    },
    {
      aliases: ['甜', '甜味', 'sweet', '甘甜', '蜜'],
      icon: 'fa-candy-cane',
      id: 'flavor_sweet',
      primaryEn: 'Sweet & Lush',
      primaryZh: '甘甜圓潤',
    },
    {
      aliases: ['苦', '苦味', 'bitter', '藥草苦', '金巴利'],
      icon: 'fa-mortar-pestle',
      id: 'flavor_bitter',
      primaryEn: 'Bitter & Complex',
      primaryZh: '深沉苦韻',
    },
    {
      aliases: ['氣泡', '氣泡感', 'bubbly', 'effervescent', '蘇打', '通寧'],
      icon: 'fa-champagne-glasses',
      id: 'flavor_bubbly',
      primaryEn: 'Effervescent & Bubbly',
      primaryZh: '輕盈氣泡',
    },
    {
      aliases: ['果香', '水果', 'fruity', 'fruit', '柑橘', '莓果'],
      icon: 'fa-apple-whole',
      id: 'flavor_fruity',
      primaryEn: 'Fruity',
      primaryZh: '果香奔放',
    },
    {
      aliases: ['花香', 'floral', '接骨木', '玫瑰', '薰衣草'],
      icon: 'fa-spa',
      id: 'flavor_floral',
      primaryEn: 'Floral',
      primaryZh: '優雅花香',
    },
    {
      aliases: ['草本', '植物', 'herbal', 'botanical', '薄荷', '迷迭香'],
      icon: 'fa-seedling',
      id: 'flavor_herbal',
      primaryEn: 'Herbal & Botanical',
      primaryZh: '草本植物',
    },
    {
      aliases: ['煙燻', '泥煤', 'smoky', 'peaty', '木質', '桶香'],
      icon: 'fa-fire',
      id: 'flavor_smoky',
      primaryEn: 'Smoky & Peaty',
      primaryZh: '煙燻木質',
    },
    {
      aliases: ['辣', '辛香', 'spicy', '生薑', '肉桂', '胡椒'],
      icon: 'fa-pepper-hot',
      id: 'flavor_spicy',
      primaryEn: 'Spicy & Warm',
      primaryZh: '辛辣溫暖',
    },
    {
      aliases: ['清爽', '消暑', 'crisp', 'refreshing', '解渴'],
      icon: 'fa-snowflake',
      id: 'flavor_refresh',
      primaryEn: 'Crisp & Refreshing',
      primaryZh: '冰涼消暑',
    },
  ],
  glasses: [
    {
      aliases: ['rocks', 'old fashioned', '低球杯', '古典杯'],
      id: 'glass_rocks',
      primaryEn: 'Old Fashioned / Rocks Glass',
      primaryZh: '古典杯 / 低球杯',
    },
    {
      aliases: ['martini', 'cocktail glass', '馬丁尼', '三角杯'],
      id: 'glass_martini',
      primaryEn: 'Martini / Cocktail Glass',
      primaryZh: '馬丁尼杯',
    },
    {
      aliases: ['coupe', '香檳杯', '碟型杯'],
      id: 'glass_coupe',
      primaryEn: 'Coupe Glass',
      primaryZh: '碟型香檳杯',
    },
    {
      aliases: ['highball', 'collins', '高球', '長飲杯'],
      id: 'glass_highball',
      primaryEn: 'Highball / Collins Glass',
      primaryZh: '高球杯 / 可林杯',
    },
    {
      aliases: ['nick nora', 'nick and nora', '尼克諾拉'],
      id: 'glass_nick_nora',
      primaryEn: 'Nick & Nora Glass',
      primaryZh: '尼克與諾拉杯',
    },
  ],
};

export const INGREDIENT_ABV_MAP: IngredientRule[] = [
  { abv: 40, keys: ['gin', '琴酒'] },
  {
    abv: 40,
    keys: ['whiskey', 'whisky', '威士忌', 'bourbon', '波本', 'scotch', '黑麥'],
  },
  { abv: 40, keys: ['rum', '蘭姆酒', '朗姆'] },
  { abv: 38, keys: ['tequila', '龍舌蘭', 'mezcal', '梅斯卡爾'] },
  { abv: 40, keys: ['vodka', '伏特加'] },
  { abv: 40, keys: ['brandy', '白蘭地', 'cognac', '干邑'] },
  { abv: 16.5, keys: ['vermouth', '苦艾酒', '香艾酒'] },
  { abv: 25, keys: ['campari', '金巴利'] },
  { abv: 11, keys: ['aperol', '阿佩羅'] },
  { abv: 35, keys: ['cointreau', '君度', 'triple sec', '白柑橘', '橙酒'] },
  { abv: 20, keys: ['kahlua', '咖啡酒', '卡魯哇'] },
  { abv: 17, keys: ['baileys', '貝禮詩', '奶酒'] },
  { abv: 55, keys: ['chartreuse', '夏翠絲'] },
  { abv: 65, keys: ['absinthe', '艾碧斯'] },
  { abv: 30, keys: ['amaro', '阿瑪羅'] },
  { abv: 44.7, keys: ['bitters', '苦精', 'angostura'] },
  {
    abv: 0,
    keys: ['juice', '汁', '檸檬', '青檸', 'lime', 'lemon', 'orange', '柳橙', '葡萄柚', '蔓越莓'],
  },
  {
    abv: 0,
    keys: ['syrup', '糖漿', '方糖', 'sugar', '蜂蜜', 'honey', '焦糖'],
  },
  {
    abv: 0,
    keys: ['tonic', '通寧', 'soda', '蘇打', '氣泡水', 'coke', '可樂', '薑汁', 'ginger'],
  },
  {
    abv: 0,
    keys: ['water', '純水', '冷水', '茶', 'tea', '蛋白', 'egg', '奶', '牛奶', 'milk'],
  },
];

export const METHOD_DILUTION_RATES: Record<string, number> = {
  Blend: 0.45,
  Build: 0.18,
  Layer: 0.0,
  Shake: 0.33,
  Stir: 0.22,
};

export const BASE_SPIRITS: BaseSpiritOption[] = [
  { id: 'Gin', label: '琴酒 Gin', nameEn: 'Gin', nameZh: '琴酒' },
  { id: 'Whiskey', label: '威士忌 Whisky', nameEn: 'Whisky', nameZh: '威士忌' },
  { id: 'Rum', label: '蘭姆酒 Rum', nameEn: 'Rum', nameZh: '蘭姆酒' },
  { id: 'Tequila', label: '龍舌蘭 Tequila', nameEn: 'Tequila', nameZh: '龍舌蘭' },
  { id: 'Vodka', label: '伏特加 Vodka', nameEn: 'Vodka', nameZh: '伏特加' },
  { id: 'Brandy', label: '白蘭地 Brandy', nameEn: 'Brandy', nameZh: '白蘭地' },
  { id: 'Other', label: '其他/無酒精', nameEn: 'Other / Mocktail', nameZh: '其他 / 無酒精' },
];
